#!/usr/bin/env python3
"""Apply independently prepared first-coder labels to the final-search sheet.

The label map is maintained without reading the second-coder decision columns.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent
PATH = ROOT / "data" / "final_multisource_search_20260730_first_coder.csv"


LABELS: dict[str, dict[str, str]] = {
    "FMS0105": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The LLM iteratively refines an audit plan from intermediate findings and static-analysis context.",
        "final_lifecycle_coverage": "candidate analysis;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports benchmark-scoped smart-contract vulnerability judgments under the reported audit plan; does not establish independently reproducible triggers for the additional CVE findings.",
    },
    "FMS0109": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Specialized agents exchange retained findings and iteratively revise smart-contract assessments.",
        "final_lifecycle_coverage": "candidate analysis;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports vulnerability classification on the reported smart-contract dataset; stronger discovery claims require item-level executable validation or aligned external records.",
    },
    "FMS0134": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The repair agent executes PoCs, inspects debugger and sanitizer state, revises patches, and re-executes validation.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports repair success for the reported projects where the PoC, crash state, and post-patch execution agree; it does not establish general repair effectiveness beyond those environments.",
    },
    "FMS0152": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "A ReAct-style agent routes binary-analysis and debugger tools and validates hypotheses with debugger-observed PoC crashes.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports debugger-verified PoC crashes for the evaluated COTS binaries and bug classes; broader binary vulnerability discovery requires additional targets and externally aligned findings.",
    },
    "FMS0212": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The agent orchestrates reconnaissance and exploitation, repairs invalid commands, and retains command-specific state across steps.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports end-to-end completion on the reported Metasploitable services; it does not by itself establish open-world discovery or independently confirmed vulnerabilities.",
    },
    "FMS0214": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Planner and interpreter components execute shell commands, inspect outputs, and update or stop the attack plan.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports autonomous shell-task completion in the reported defender and Bandit settings; stronger vulnerability claims require target-specific validation artifacts.",
    },
    "FMS0226": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "ReaperAI executes offensive-security actions, feeds operational results back to the model, and retains context across a task trajectory.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;governance / human gates / disclosure control",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports controlled exploitation tasks on the reported training platforms; it does not establish independently confirmed vulnerability discovery in external targets.",
    },
    "FMS0254": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "CHECKMATE combines explicit classical plans with LLM command generation and environment feedback for long-horizon pentesting.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports completion of the reported penetration-testing milestones under the benchmark plan and environment; it does not establish general vulnerability discovery outside that task set.",
    },
    "FMS0257": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The workflow retrieves CVE context, generates reproduction assets, executes them, and records whether the disclosed behavior is reproduced.",
        "final_lifecycle_coverage": "candidate analysis;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports reproduction of the reported subset of public CVEs across specified libraries and environments; it does not establish novel vulnerability discovery.",
    },
    "FMS0267": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Specialized agents generate and verify security patches in an iterative vulnerability-verifier feedback loop.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports patch validation for the evaluated real-world CVE cases under the reported verifier; stronger deployment claims require maintained builds and independent regression confirmation.",
    },
    "FMS0269": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "AutoPenBench executes generative pentesting agents in a standardized environment and records their multi-step actions and outcomes.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports comparative task completion for evaluated agents on the 33 benchmark tasks; it does not establish open-world vulnerability discovery.",
    },
    "FMS0270": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "AutoPentest queries an LLM for commands and state updates while executing a black-box penetration-test trajectory.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports autonomous black-box penetration-testing subtasks in the reported benchmark environment; stronger vulnerability claims require aligned per-target validation artifacts.",
    },
    "FMS0271": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "AutoPentester chooses security tools, interprets their outputs, and generates the next attack strategy across iterations.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports subtask completion and vulnerability coverage on Hack The Box and custom targets; it does not independently establish general discovery effectiveness.",
    },
    "FMS0272": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "AutoPT executes a complete web-pentesting process and uses environment observations to update subsequent agent actions.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports end-to-end web-pentesting completion in the proposed benchmark scenarios; stronger real-world discovery claims require item-level external validation.",
    },
    "FMS0281": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "AWE uses memory-augmented agents and vulnerability-specific pipelines to adapt web testing to observed target behavior.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports runtime-grounded web vulnerability findings in the evaluated applications; stronger reproducibility claims require complete replay inputs and environments.",
    },
    "FMS0284": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "BACFuzz adjusts request generation using runtime feedback and applies a SQL-based oracle to silent authorization failures.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports oracle-backed broken-access-control signals on the evaluated web applications; the reported new vulnerabilities require public item-level confirmation for external traceability.",
    },
    "FMS0288": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The study executes coding-agent baselines that inspect workspaces, issue commands, and iterate from environment feedback on pentesting tasks.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports comparative task success for default and specialized agents under matched benchmark conditions; it does not establish a general vulnerability-discovery ranking.",
    },
    "FMS0372": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Chai builds protocol context, routes analysis and validation actions, and follows naturally occurring signals to validate cryptographic misuse hypotheses.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports validated cryptographic-misuse behavior in the evaluated libraries; the reported previously unknown issue remains author-reported without item-level public alignment.",
    },
    "FMS0389": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The LLM generates executable knowledge-graph queries and an auxiliary agent feeds feasibility results back into later query refinement.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;failure reuse / strategy update",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports access-control vulnerability judgments on the evaluated smart-contract datasets; stronger exploitability claims require executable validation.",
    },
    "FMS0401": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Cochise supplies a planner-executor harness that issues SSH commands, keeps long-term state, and records trajectories and side effects.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;governance / human gates / disclosure control",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports auditable execution trajectories and controlled pentesting tasks in the reference harness; it does not itself establish new vulnerability findings.",
    },
    "FMS0435": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Multiple LLM modules plan and execute Kali command-line tools while iterative feedback refines later actions.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports semi-autonomous penetration-testing task execution in the reported environments; stronger vulnerability claims require target-level validation material.",
    },
    "FMS0489": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "CVE-Bench executes repair agents in containerized repositories and validates generated patches with vulnerability-specific tests.",
        "final_lifecycle_coverage": "candidate analysis;patch validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports vulnerability-repair success on containerized public CVE cases when patches apply and tests pass; it does not establish deployment readiness beyond the benchmark.",
    },
    "FMS0500": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "D-CIPHER dynamically coordinates planner and heterogeneous executor agents that run tools and revise CTF strategies from feedback.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports CTF task completion under the reported benchmarks and models; it does not directly establish target-software vulnerability discovery.",
    },
    "FMS0509": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The evaluation runs agents through separated reconnaissance and exploit-execution stages with standardized tools and ground-truth contexts.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports stage-specific reconnaissance and exploitation success against known benchmark targets; it does not establish open-world vulnerability discovery.",
    },
    "FMS0538": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Diffploit iteratively interprets build and runtime failures to adapt exploits across affected library versions and revalidates them.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports exploit migration and re-execution across the evaluated Java CVE versions; broader transfer claims require additional ecosystems and independent replay.",
    },
    "FMS0541": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "KLEECopilot converts LLM-selected security regions into KLEE path priorities and returns concrete violation-triggering inputs.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports concrete KLEE inputs for security violations reached under the reported prioritization and targets; broader discovery claims require additional programs and independent replay.",
    },
    "FMS0598": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The LangGraph workflow executes penetration-testing actions and updates a shared graph memory from observed environment state.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update;governance / human gates / disclosure control",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports environment-grounded trajectories in the reported robotics CTF setting; it does not establish open-world vulnerability discovery.",
    },
    "FMS0619": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Multiple agents divide vulnerability analysis, patch generation, and code validation and execute the resulting repair workflow.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports validated repair outcomes for the evaluated vulnerable-code cases; stronger generalization claims require broader repositories and independent regression testing.",
    },
    "FMS0648": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Agentic analyses inspect generated crashes and caller reachability to decide whether OSS-Fuzz-Gen reports represent target behavior.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports false-crash triage for the evaluated OSS-Fuzz-Gen cases; a positive vulnerability claim still requires a reachable, reproducible project-level trigger.",
    },
    "FMS0650": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "FaultLine generates, builds, executes, and revises proof-of-vulnerability tests in a feedback-driven loop.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports buildable and executable PoV tests for the evaluated vulnerability reports; stronger claims require independent replay against aligned versions and environments.",
    },
    "FMS0676": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The study executes singular and modular agents that generate payloads and adapt actions to network feedback in reproducible pentesting tasks.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports architecture-level comparisons on the curated penetration-testing tasks; it does not establish a general system ranking or novel vulnerability discovery.",
    },
    "FMS0684": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "A ReAct agent selects interprocedural context tools, observes their outputs, and iterates before classifying security patches.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports security-patch classification on the reported dataset; it does not by itself validate vulnerability behavior or patch effectiveness.",
    },
    "FMS0698": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "T2L-Agent gathers stack-trace and repository evidence through a planner-executor loop to update vulnerability localization decisions.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports source-line localization for the expert-verified benchmark cases; the localization alone does not establish exploitability or a reproducible trigger.",
    },
    "FMS0718": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "GapForge turns measured coverage gaps and failed prompts into new compiler-fuzzing targets and concrete generated tests.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports concrete compiler tests and reported violation discovery for the evaluated GCC and LLVM versions; broader claims require independent replay of each finding.",
    },
    "FMS0733": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "GoAT-X grounds graph-of-thought planning in statically extracted data flows and validates candidate cross-chain logic risks through analysis operations.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports benchmark-scoped cross-chain risk judgments and author-reported wild findings; stronger claims require item-level public validation of the reported risks.",
    },
    "FMS0734": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "GPTScan uses LLM-selected key variables and statements to drive subsequent static confirmation.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;validation organization / evidence packaging",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports statically confirmed logic-vulnerability candidates on the evaluated contract datasets; exploitability and runtime behavior require additional validation.",
    },
    "FMS0741": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Structured attack trees constrain LLM planning while tool results feed a closed loop for subsequent pentesting actions.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports successful cyberattack subtasks in the reported structured benchmark; it does not establish open-world vulnerability discovery.",
    },
    "FMS0747": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "HackSynth's planner and summarizer modules execute commands and iteratively process environment feedback across CTF tasks.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports autonomous completion on the reported CTF benchmark sets; stronger software-vulnerability claims require target-specific validation material.",
    },
    "FMS0753": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "SeedMind repeatedly feeds coverage progress to the LLM to refine seed generation for subsequent greybox fuzzing.",
        "final_lifecycle_coverage": "path and input exploration;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports coverage-guided seed generation and fuzzing progress on the evaluated programs; coverage improvement alone does not establish a vulnerability.",
    },
    "FMS0768": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Hound retrieves relation-grounded code slices, updates hypothesis confidence from evidence, and confirms or rejects audit candidates.",
        "final_lifecycle_coverage": "candidate analysis;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports vulnerability-hypothesis judgments on the evaluated audit benchmark projects; stronger claims require executable or externally aligned validation.",
    },
    "FMS0842": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "RefPentester retrieves structured attack knowledge, executes steps, and uses a reflector to turn execution feedback into later actions.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports credential capture and stage-transition completion on the reported Hack The Box target; it does not establish open-world vulnerability discovery.",
    },
    "FMS0850": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "HyLLFuzz combines concolic execution with LLM reasoning and returns coverage validation to guide subsequent hybrid-fuzzing inputs.",
        "final_lifecycle_coverage": "path and input exploration;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports coverage-oriented hybrid-fuzzing performance on the evaluated benchmarks; coverage gains alone do not establish a vulnerability.",
    },
    "FMS0890": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "LibLMFuzz routes disassembly, compilation, and fuzzing tools and iteratively repairs generated fuzz targets from build or runtime errors.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports autonomous construction and execution of fuzz targets for the evaluated black-box libraries; stronger vulnerability claims require concrete crash or replay evidence.",
    },
    "FMS0904": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The study executes 20 agents against concrete web vulnerabilities and assesses whether they can construct and run reproduction workflows.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports agent reproduction success for three reported web vulnerabilities in controlled environments; it does not establish general web-vulnerability discovery.",
    },
    "FMS0914": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Six agents exchange retrieved context and structured feedback across detection, cause analysis, repair suggestion, and risk assessment.",
        "final_lifecycle_coverage": "candidate analysis;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports smart-contract vulnerability-management judgments on the reported dataset; repair and exploitability claims require executable validation.",
    },
    "FMS0922": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "LLM-JDFuzz switches among generation, mutation, and semantic exploration based on execution errors and iteratively refines payloads.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports executable Java deserialization payload generation for the evaluated ysoserial gadget chains; broader exploit claims require aligned target versions and environments.",
    },
    "FMS0927": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "LLM4CVE iteratively revises vulnerability patches from compiler and evaluation feedback and validates the resulting code.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports compiler- and test-validated repairs for the evaluated CVE cases; stronger deployment claims require independent regression and maintenance evidence.",
    },
    "FMS0933": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The framework fuzz-tests LLM-generated weakest preconditions and feeds validity and weakness results back into later generation.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;failure reuse / strategy update;validation organization / evidence packaging",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports fuzzing-assisted weakest-precondition synthesis on the deterministic Java benchmark; it does not directly establish a software vulnerability.",
    },
    "FMS0935": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "MOJOFuzzer updates LLM mutation prompts from runtime feedback and re-executes generated tests.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports runtime bug signals and coverage gains for the evaluated MOJO environment; stronger vulnerability claims require reproducible, version-aligned triggers.",
    },
    "FMS0945": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Locus synthesizes target predicates, observes directed-fuzzing progress, and refines guidance until target program states are reached.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports concrete inputs reaching reported target states under the evaluated fuzzers; vulnerability claims depend on the security meaning and replay of each target state.",
    },
    "FMS0964": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "A supervisor delegates security-policy checks to tool-using executor agents and updates decisions from their returned results.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports RTL security-bug judgments on the evaluated OpenTitan design and benchmark; stronger hardware vulnerability claims require executable or formal item-level validation.",
    },
    "FMS0966": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "MASFuzzer generates and mutates drivers while a coverage-guided scheduler reallocates execution to promising API sequences.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports coverage and runtime findings produced by generated drivers on the evaluated libraries; stronger vulnerability claims require replayable, security-relevant triggers.",
    },
    "FMS0969": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "FUEL interprets multiple runtime feedback types, repairs invalid executions, and uses them to guide subsequent deep-learning-framework fuzzing.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports runtime bug signals on the evaluated deep-learning frameworks; reported real-world findings require public item-level alignment for stronger claims.",
    },
    "FMS1017": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The web pentesting system orchestrates tactical agents over tool outputs and requires proof-of-concept validation for reported findings.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update;governance / human gates / disclosure control",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports PoC-validated findings in the evaluated web applications; the reported CVE status remains author-reported until item-level public records align.",
    },
    "FMS1024": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Mystique generates cross-version patches and iteratively checks and refines them against the target vulnerable function and project tests.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports validated patch porting for the reported real-world vulnerability cases; deployment claims require independent regression and maintained-version evidence.",
    },
    "FMS1034": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "MoCQ executes LLM-generated static-analysis patterns and uses trace-driven symbolic feedback to refine later pattern generations.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;failure reuse / strategy update",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports vulnerability-pattern generation and candidate findings on the evaluated programs; the reported new vulnerabilities require item-level public alignment or reproducible triggers for stronger claims.",
    },
    "FMS1055": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "LASiR combines static taint results with LLM semantic inspection to confirm or reject signature-replay warnings.",
        "final_lifecycle_coverage": "candidate analysis",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports candidate classification for signature-replay vulnerabilities in the evaluated contract datasets; runtime exploitability requires an aligned executable trigger.",
    },
    "FMS1063": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Orion coordinates harness creation, fuzzing, crash triage, and patch checking through iterative tool feedback and retained workflow state.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;patch validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports reproduced crashes and checked repairs in the evaluated fuzzing workflows; the reported zero-day outcomes require public item-level disclosure records for external alignment.",
    },
    "FMS1083": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PenForge probes targets, constructs specialist agents on demand, and revises exploitation actions from environment feedback.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports successful exploit tasks on the stated benchmark instances; broader vulnerability-discovery claims require results outside the bounded benchmark and aligned validation material.",
    },
    "FMS1087": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PentestEval executes modular penetration-testing agents across staged environments and records intermediate and terminal task outcomes.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports stage-level and end-to-end penetration-testing performance on the benchmark environments; it does not by itself establish open-world vulnerability discovery.",
    },
    "FMS1088": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PentestMCP uses specialist agents, an MCP tool interface, retrieval, and a penetration task graph to coordinate information gathering, discovery, and exploitation.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports phase-level completion rates in the reported penetration-testing setting; vulnerability-specific claims require aligned exploit or replay material.",
    },
    "FMS1093": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PILOT derives paths to target functions, iteratively regenerates CLI inputs from coverage feedback, and executes the resulting fuzzing campaigns.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "externally traceable material",
        "final_external_traceability": "publicly aligned external trace",
        "final_claim_boundary": "Supports the reported fuzzing findings whose triggering cases are linked to maintainer confirmation, fixes, or CVE records; the claim remains limited to the evaluated CLI programs and disclosed items.",
    },
    "FMS1095": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PoCEvolve generates PoCs from patches and uses validation failures to evolve later prompts and candidates.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports validated PoC generation from security patches for the evaluated CVEs; it does not establish discovery of previously unknown vulnerabilities.",
    },
    "FMS1096": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PoCGen iteratively constructs and executes JavaScript exploits, using runtime information and validation feedback to refine later attempts.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "publicly aligned external trace",
        "final_claim_boundary": "Supports executable PoCs for the evaluated npm vulnerabilities, including PoCs linked to public advisories; it does not establish open-world vulnerability discovery.",
    },
    "FMS1098": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "PoCo decomposes auditor reports into tool-mediated smart-contract PoC construction and checks generated exploits against vulnerable and patched behavior.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports executable PoCs for the evaluated smart-contract audit reports under the supplied project environments; stronger generalization claims require broader independent cases.",
    },
    "FMS1135": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "QLCoder synthesizes CodeQL queries in an execution-feedback loop and checks that they match vulnerable versions but remain silent on patched versions.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports executable vulnerability queries validated across recorded vulnerable and patched versions; broader detection claims require independent variant-analysis results.",
    },
    "FMS1136": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "QLPro uses cooperating LLM roles to generate, compile, repair, and execute CodeQL rules for vulnerability discovery.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;failure reuse / strategy update",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports CodeQL-based candidate findings on the evaluated projects; the reported officially confirmed zero-day findings need item-level public records or triggers for a stronger external claim.",
    },
    "FMS1149": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "RapidPen repeatedly scans, selects attack actions, executes tools, and uses observed results and retained prior experience to reach shell access.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports IP-to-shell completion on the reported Hack The Box target and conditions; it does not establish general vulnerability-discovery performance.",
    },
    "FMS1161": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Red-MIRROR coordinates specialist pentesting agents through shared memory, retrieval, reflection, tool execution, and attack-response verification.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports benchmark penetration-testing completion under the evaluated memory and reflection configuration; vulnerability-specific claims require aligned replay or disclosure material.",
    },
    "FMS1227": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "SAVANT combines dependency records, patch-provided PoV tests, reachability analysis, and iterative LLM context expansion to classify vulnerable API use.",
        "final_lifecycle_coverage": "candidate analysis;execution observation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports dependency-vulnerability classifications for the evaluated projects and public PoV-backed cases; application exploitability requires an aligned executable trigger in the target context.",
    },
    "FMS1239": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "SEC-bench Pro executes long-horizon coding agents on containerized real vulnerabilities and uses dynamic and LLM-based judges to validate generated PoCs.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports dynamically validated PoC completion on the versioned SEC-bench Pro instances; it does not establish open-world discovery outside the benchmark.",
    },
    "FMS1261": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "SecureFixAgent turns Bandit findings into iterative LLM repairs and validates subsequent versions against static checks and project tests.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports patches that pass the reported static and test checks for the evaluated Python cases; deployment safety requires independent regression and maintained-version evidence.",
    },
    "FMS1275": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The firmware workflow scans generated code, proposes patches, executes validation in a virtualized environment, and iteratively refines failed repairs.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "no external trace reported",
        "final_claim_boundary": "Supports checked repairs for the evaluated generated firmware in the stated virtualized environment; real-device and maintained-version claims require independent validation.",
    },
    "FMS1279": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "Smartify delegates smart-contract auditing, repair planning, generation, refinement, and validation across specialist agents in an iterative workflow.",
        "final_lifecycle_coverage": "candidate analysis;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports validated Solidity and Move repairs under the reported datasets and checks; production safety requires independent regression and deployment evidence.",
    },
    "FMS1338": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The study executes coding agents with repository tools and iterative reasoning to filter and explain static-analysis alerts.",
        "final_lifecycle_coverage": "candidate analysis",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports false-positive filtering decisions for the evaluated static-analysis alerts; runtime exploitability requires execution or replay evidence.",
    },
    "FMS1492": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "The study builds and evaluates offensive-security agents that plan, execute tools, receive environment feedback, and complete CTF tasks under varied configurations.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports CTF task performance and trajectory-level capability findings on the reported benchmark; it does not establish open-world vulnerability discovery.",
    },
    "FMS1509": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "TRACE combines repository context, static program information, and iterative LLM completion to identify smart-contract access-control vulnerabilities.",
        "final_lifecycle_coverage": "candidate analysis;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;feedback interpretation / loop adjustment;validation organization / evidence packaging",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports access-control candidate findings on the evaluated contract repositories and public vulnerability dataset; executable exploitability requires aligned runtime validation.",
    },
    "FMS1514": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "CTF-Dojo trains and evaluates language-model agents in containerized security environments with tool execution and verified task feedback.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports executable CTF task completion in the containerized environments; the result does not by itself establish discovery on unseen production software.",
    },
    "FMS1561": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "VCAO maintains a vulnerability belief state and routes CodeQL, fuzzing, KASAN/KCSAN, patch mining, and verification tools according to observed feedback.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation;patch validation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "author-reported external clue",
        "final_claim_boundary": "Supports verifier-backed runtime findings under the evaluated OS snapshots and tool budget; reported live discoveries require public item-level alignment for stronger external claims.",
    },
    "FMS1586": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "VulnBot coordinates reconnaissance, scanning, exploitation, error handling, and feedback across multiple pentesting agents and tools.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports completed penetration-testing tasks on the reported benchmark and vulnerable machines; vulnerability-discovery claims remain bounded to those environments.",
    },
    "FMS1607": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "LoopRepair localizes vulnerable statements, generates patches, uses PoV and trace constraints to select candidates, and iteratively refines failed repairs.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports patches that satisfy the reported PoV, trace, and test constraints for the evaluated vulnerabilities; deployment claims require independent regression evidence.",
    },
    "FMS1613": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "VerifiaBLE uses LLMs to translate application logic into formal models, iteratively refines the translation, and invokes ProVerif to identify security violations.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;reporting and audit",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "candidate-analysis system",
        "final_principal_reported_evidence_output": "candidate judgment",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports formally derived vulnerability candidates for the evaluated Bluetooth Low Energy applications; concrete exploitability requires an aligned runtime trigger.",
    },
    "FMS1618": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "ChipFuzzer interprets RTL semantics and coverage feedback to generate and refine later test cases against a simulated design under test.",
        "final_lifecycle_coverage": "path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;failure reuse / strategy update",
        "final_primary_system_shape": "feedback-driven fuzzing agent",
        "final_principal_reported_evidence_output": "runtime safety signal",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports simulation and coverage-linked RTL bug signals under the evaluated designs; hardware vulnerability claims require replayable failing tests and implementation-level validation.",
    },
    "FMS1635": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "xOffense decomposes penetration testing among specialist agents and iteratively updates a task graph from command outputs and feedback analysis.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports subtask and end-to-end penetration-testing completion on the stated benchmarks; it does not establish general vulnerability discovery beyond them.",
    },
    "FMS1639": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "ZERO-APT closes the loop among attacker, defender, and judge agents, updating plans from ReAct feedback under constrained action policies.",
        "final_lifecycle_coverage": "candidate analysis;path and input exploration;execution observation;reproduction and validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update;governance / human gates / disclosure control",
        "final_primary_system_shape": "long-horizon pentest and CRS agent",
        "final_principal_reported_evidence_output": "controlled task completion",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports attack-chain completion under the reported adaptive-defense environment and action constraints; it does not establish unrestricted real-world exploitability.",
    },
    "FMS1640": {
        "eligibility_decision": "include_study_level",
        "eligibility_reason": "ZeroDayBench executes coding agents on unseen, versioned vulnerability variants and verifies proposed patches against benchmark tests and exploit criteria.",
        "final_lifecycle_coverage": "candidate analysis;execution observation;patch validation",
        "final_cross_stage_capabilities": "context aggregation / rule extraction;tool routing / strategy routing;feedback interpretation / loop adjustment;validation organization / evidence packaging;long-horizon state management;failure reuse / strategy update",
        "final_primary_system_shape": "reproduction-, validation-, and repair-centered agent",
        "final_principal_reported_evidence_output": "reproducible validation",
        "final_external_traceability": "benchmark ground truth / public material",
        "final_claim_boundary": "Supports patch success on the benchmark's constructed unseen vulnerability variants under its test and exploit oracles; it does not establish repair of naturally emerging zero-days.",
    },
}


def main() -> int:
    with PATH.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        fields = list(reader.fieldnames or [])
        rows = list(reader)
    known = {row["discovery_id"] for row in rows}
    unknown = sorted(set(LABELS) - known)
    if unknown:
        raise SystemExit(f"ERROR unknown first-coder IDs: {unknown}")
    for row in rows:
        labels = LABELS.get(row["discovery_id"])
        if not labels:
            continue
        for key, value in labels.items():
            row[key] = value
        row["material_checked"] = f"public full text; {row['public_fulltext_url']}"
        row["decision_note"] = "Independent first-coder assessment under the frozen codebook."
        row["uncertainty_note"] = ""
        row["row_status"] = "complete"
    with PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    print(f"APPLIED={len(LABELS)} TOTAL={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
